stages:
  - build

build_image:
    stage: build
    image: docker:1.13.1
    services:
        - docker:1.13.1-dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    only:
        - develop
        - master
        - tags
    tags:
        - container